[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_platform = "6Py5RKvhAAbqWcHjavqkNdtMaMm6TDLGovDEynNzFPX9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ashutosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
